[package]
name = "chipolata"
version = "1.0.0"
authors = ["William Durand <will+git@drnd.me>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
structopt = "0.3.13"
minifb = "0.19.1"
rand = "0.8.1"
rodio = "0.13.0"
